name: Package and Publish Frontend 📦
description: |
  This composite action packages and publishes the frontend application
  (lyra-app and lyra-landing-page) to the container registry. It also performs vulnerability scanning.

inputs:
  deliver:
    description: 'Deliver frontend to production'
    required: true
    default: 'true'
  docker_username:
    description: 'The username for Docker Hub'
    required: true
  docker_password:
    description: 'The password for Docker Hub'
    required: true
  version:
    description: 'The version of the frontend'
    required: true
  ci_github_token:
    description: 'GITHUB_TOKEN with permissions to push to the container registry'
    required: true
  target:
    description: 'The target image to build (lyra-app, lyra-landing-page)'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Docker Hub and GHCR
      run: |
        echo ${{ inputs.ci_github_token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        echo ${{ inputs.docker_password }} | docker login docker.io -u ${{ inputs.docker_username }} --password-stdin
      shell: bash

    - name: Cache Docker layers
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        target: ${{ inputs.target }}
        push: ${{ inputs.deliver }}
        tags: |
          ghcr.io/dallay/${{ inputs.target }}:${{ inputs.version }},
          ghcr.io/dallay/${{ inputs.target }}:latest,
          docker.io/${{ inputs.target }}:${{ inputs.version }},
          docker.io/${{ inputs.target }}:latest
        cache-from: type=registry,ref=ghcr.io/dallay/${{ inputs.target }}:cache
        cache-to: type=registry,ref=ghcr.io/dallay/${{ inputs.target }}:cache,mode=max

    - name: 🪄 Scan Docker images for vulnerabilities
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/dallay/${{ inputs.target }}:${{ inputs.version }}
        format: sarif
        output: trivy-${{ inputs.target }}-report.sarif
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        cache-dir: /tmp/trivy-cache-${{ inputs.target }}

    - name: ⇪ Upload Trivy Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-${{ inputs.target }}-report
        path: trivy-${{ inputs.target }}-report.sarif
