name: Package and Publish Frontend 📦
description: |
  This composite action packages and publishes the frontend application
  (lyra-app and lyra-landing-page) to the container registry. It also performs vulnerability scanning.

inputs:
  deliver:
    description: 'Deliver frontend to production'
    required: true
    default: 'true'
  docker_username:
    description: 'The username for Docker Hub'
    required: true
  docker_password:
    description: 'The password for Docker Hub'
    required: true
  version:
    description: 'The version of the frontend'
    required: true
  ci_github_token:
    description: 'GITHUB_TOKEN with permissions to push to the container registry'
    required: true
  target:
    description: 'The target image to build (lyra-app, lyra-landing-page)'
    required: true
  non_prod_tag:
    description: 'Non production docker image tag'
    required: false
    default: 'nightly'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ci_github_token }}

    - name: Cache Docker layers
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        target: ${{ inputs.target }}
        push: true
        tags: |
          ghcr.io/dallay/${{ inputs.target }}:${{ inputs.deliver == 'true' ? inputs.version : inputs.non_prod_tag }},
          ghcr.io/dallay/${{ inputs.target }}:${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }},
          docker.io/n4t5u/${{ inputs.target }}:${{ inputs.deliver == 'true' ? inputs.version : inputs.non_prod_tag }},
          docker.io/n4t5u/${{ inputs.target }}:${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }}
        cache-from: type=registry,ref=ghcr.io/dallay/${{ inputs.target }}:cache
        cache-to: type=registry,ref=ghcr.io/dallay/${{ inputs.target }}:cache,mode=max

    - name: 🪄 Scan Docker images for vulnerabilities
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/dallay/${{ inputs.target }}:${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }}
        format: sarif
        output: trivy-${{ inputs.target }}-report-${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }}.sarif
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        cache-dir: /tmp/trivy-cache-${{ inputs.target }}-${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }}

    - name: ⇪ Upload Trivy Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-${{ inputs.target }}-report-${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }}
        path: trivy-${{ inputs.target }}-report-${{ inputs.deliver == 'true' ? 'latest' : inputs.non_prod_tag }}.sarif
