#!/usr/bin/env bash

echo "Running pre-commit hook 🪝"

# This script is used to run the formatter, linter, and tests before a commit.

# Determine the package manager being used
if command -v pnpm >/dev/null 2>&1; then
	PACKAGE_MANAGER="pnpm"
elif command -v yarn >/dev/null 2>&1; then
	PACKAGE_MANAGER="yarn"
elif command -v npm >/dev/null 2>&1; then
	PACKAGE_MANAGER="npm"
else
	echo "No package manager found installed."
	exit 1
fi

echo "🟢 Using package manager: $PACKAGE_MANAGER"

if $PACKAGE_MANAGER install && $PACKAGE_MANAGER run format && $PACKAGE_MANAGER run lint && $PACKAGE_MANAGER run test; then
	exit 0
else
	echo "Error: ❌ failed to run pre-commit hook"
	exit 1
fi


# Gradle pre-commit hook ./gradlew detektAll Fail if detekt fails

if ! ./gradlew detektAll; then
    echo "Error: ❌ failed to run pre-commit hook"
    exit 1
fi

