version: 2
updates:
  - package-ecosystem: "docker"  # First ecosystem
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"  # Second ecosystem
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"  # Third ecosystem
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"  # Fourth ecosystem
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"  # Fifth ecosystem
    directory: "/"
    schedule:
      interval: "weekly"
