services:
  db:
    image: postgres:12.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgresql/data:/var/lib/postgresql/data
