<script lang="ts" setup>
import { reactive } from 'vue';
import QrcodeImage from 'vue-qrcode-image';
import { XBreadcrumb, XButton, XTextField } from '@lyra/ui';

const flux = reactive({
	os: 'ios',

	flow: 1,
});
</script>

<template>
	<XBreadcrumb :items="[{ text: 'Settings' }, { text: 'Two-factor Authentication' }]" />

	<h1 class="my-4 text-4xl font-extrabold">Two-factor Authentication</h1>

	<div class="w-125 rounded-md bg-white px-6 py-5 shadow-lg dark:bg-slate-800">
		<div class="text-xl font-bold">Turn on Two-step Verification</div>

		<template v-if="flux.flow === 1">
			<div class="mb-6 mt-3">Get verification codes with Google Authenticator</div>

			<div
				class="relative flex w-full rounded-t-xl bg-slate-50 p-3 shadow transition-colors dark:bg-slate-700"
			>
				<input
					id="radio-1"
					v-model="flux.os"
					type="radio"
					name="tabs"
					value="ios"
					class="z-2 hidden"
				/>
				<label
					class="z-2 flex h-12 flex-1 cursor-pointer items-center justify-center border-b border-slate-500 font-bold"
					for="radio-1"
					>iPhone & iPad</label
				>
				<input
					id="radio-2"
					v-model="flux.os"
					type="radio"
					name="tabs"
					value="android"
					class="z-2 hidden"
				/>
				<label
					class="z-2 flex h-12 flex-1 cursor-pointer items-center justify-center border-b border-slate-500 font-bold"
					for="radio-2"
					>Android</label
				>
				<span
					class="glider z-1 border-primary-500 absolute flex h-12 border-b-2 transition-transform"
				></span>
			</div>

			<div
				class="mb-6 flex items-center justify-center rounded-b bg-slate-50 p-4 pb-7 dark:bg-slate-700"
			>
				<QrcodeImage
					v-if="flux.os === 'ios'"
					value="https://apps.apple.com/app/google-authenticator/id388497605"
					:size="5"
					class="w-50 rounded-md"
				/>

				<QrcodeImage
					v-if="flux.os === 'android'"
					value="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"
					:size="4"
					class="w-50 rounded-md"
				/>
			</div>

			<div class="flex justify-center">
				<XButton class="w-1/3" @click="flux.flow = 2">Next</XButton>
			</div>
		</template>

		<template v-if="flux.flow === 2">
			<div class="mb-6 mt-3">Scan the QR code into your app.</div>

			<div
				class="mb-6 flex items-center justify-center rounded bg-slate-50 px-4 py-7 dark:bg-slate-700"
			>
				<QrcodeImage
					value="otpauth://totp/Fastify%20Starter:yap?secret=CANACAIVIRPXM23E&period=30&digits=6&algorithm=SHA1&issuer=Fastify%20Starter"
					:size="4"
					class="w-50 rounded-md"
				/>
			</div>

			<div class="flex justify-center gap-4">
				<XButton color="secondary" class="w-1/3" @click="flux.flow = 1">Back</XButton>
				<XButton class="w-1/3" @click="flux.flow = 3">Next</XButton>
			</div>
		</template>

		<template v-if="flux.flow === 3">
			<div class="mb-6 mt-3">Enter the 6-digit authentication code generated by your app:</div>

			<div class="mb-6">
				<XTextField class="text-center" maxlength="6" />
			</div>

			<div class="flex justify-center gap-4">
				<XButton color="secondary" class="w-1/3" @click="flux.flow = 2">Back</XButton>
				<XButton class="w-1/3" @click="flux.flow = 4">Next</XButton>
			</div>
		</template>

		<template v-if="flux.flow === 4">
			<div class="i-lucide-check-circle m-6 mx-auto h-12 w-12 text-green-500"></div>
		</template>
	</div>
</template>

<style lang="scss" scoped>
input[type='radio'] {
	&:checked + label {
		@apply text-primary-500;
	}
}

input[id='radio-1'] {
	&:checked ~ .glider {
		@apply translate-x-0;
	}
}

input[id='radio-2'] {
	&:checked ~ .glider {
		@apply translate-x-1/1;
	}
}

.glider {
	width: 214px;
}
</style>
