name: Install Java Tools & Dependencies
description: Installs java, gradle & package dependencies

inputs:
  java-version:
    description: 'The JDK version to install'
    required: false
    type: string
    default: '21'
  gradle-arguments:
    description: 'The arguments to pass to the gradle command'
    required: false
    type: string
    default: 'projects'
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    type: string
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Java ☕
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: gradle

    - name: Gradle Wrapper Permissions
      run: |
        chmod +x gradlew
      shell: bash

    - name: ⚙️ Setup Gradle 🐘
      uses: gradle/actions/setup-gradle@v3
      id: gradle
      with:
        add-job-summary-as-pr-comment: on-failure
        arguments: ${{ inputs.gradle-arguments }}
        dependency-graph: generate-and-submit

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      if: ${{ steps.gradle.outputs.build-scan-url }}
      with:
        name: build-reports
        path: build/reports/

    - name: Add Build Scan URL as PR comment when build fails
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ steps.gradle.outputs.build-scan-url }} && github.event_name == 'pull_request' && failure()
      with:
        recreate: true
        header: build-scan-url
        message: |
          ❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Add Build Scan URL as PR comment when build succeeds
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ steps.gradle.outputs.build-scan-url }} && github.event_name == 'pull_request' && success()
      with:
        recreate: true
        header: build-scan-url
        message: |
          ✅ ${{ github.workflow }} succeeded: ${{ steps.gradle.outputs.build-scan-url }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
