name: Install Java Tools & Dependencies
description: Installs java, gradle & package dependencies

inputs:
  java-version:
    description: 'The JDK version to install'
    required: false
    default: '21'
  gradle-arguments:
    description: 'The arguments to pass to the gradle command'
    required: false
    default: 'projects'
  gradle-encription-key:
    description: 'The encryption key to use for the gradle cache'
    required: true
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Java ☕
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: gradle

    - name: Gradle Wrapper Permissions
      run: |
        chmod +x gradlew
      shell: bash

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

    - name: ⚙️ Setup Gradle 🐘
      uses: gradle/actions/setup-gradle@v4
      id: gradle
      with:
        add-job-summary-as-pr-comment: on-failure
        # arguments: ${{ inputs.gradle-arguments }}
        cache-encryption-key: ${{ inputs.gradle-encription-key }}
    - run: ./gradlew ${{ inputs.gradle-arguments }}
      shell: bash

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: ${{ steps.gradle.outputs.build-scan-url }}
      with:
        name: build-reports
        path: build/reports/
