export const HTTP_AUTHENTICATION_SERVICE = 'HTTP_AUTHENTICATION_SERVICE';
export const HTTP_AUTHENTICATION_REPOSITORY = 'HTTP_AUTHENTICATION_REPOSITORY';
export const HTTP_LOGOUT_AUTHENTICATION_REPOSITORY = 'HTTP_LOGOUT_AUTHENTICATION_REPOSITORY';
export const LOGIN_SERVICE = 'LOGIN_SERVICE';
export const LOGOUT_SERVICE = 'LOGOUT_SERVICE';
export const REFRESH_TOKEN_SERVICE = 'REFRESH_TOKEN_SERVICE';
