name: Publish to GHCR and Deploy
description: Publish the application to the GitHub Container Registry and deploy to the main stage

inputs:
  REGISTRY:
    description: 'The container registry to push the image to'
    required: true
    default: 'ghcr.io'
  IMAGE_NAME:
    description: 'The name of the image to be published'
    required: true
    default: ${{ env.IMAGE_NAME }}
  VERSION:
    description: 'The version of the application'
    required: true
    default: ${{ env.VERSION }}
  CI_GITHUB_TOKEN:
    description: 'GITHUB_TOKEN with permissions to push to the container registry'
    required: true
    default: ${{ env.CI_GITHUB_TOKEN }}
  OWNER:
    description: 'The owner of the repository'
    required: true
    default: ${{ env.OWNER }}
  APP_REPO:
    description: 'The name of the application repository'
    required: true
    default: ${{ env.APP_REPO }}

runs:
    using: composite
    steps:
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ inputs.CI_GITHUB_TOKEN }}

      - name: Publish container image
        run: |
          docker tag ${{ inputs.IMAGE_NAME }}:${{ inputs.VERSION }} ${{ inputs.REGISTRY }}/${{ inputs.OWNER }}/${{ inputs.APP_REPO }}:${{ inputs.VERSION }}
          docker push ${{ inputs.REGISTRY }}/${{ inputs.OWNER }}/${{ inputs.APP_REPO }}:${{ inputs.VERSION }}
          docker tag ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.VERSION }} \
                    ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:latest
          docker push ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:latest
        shell: bash
