name: Publish to GHCR 📦
description: |
  This workflow packages and publishes the application to GHCR and performs vulnerability scanning.

inputs:
  deliver:
    description: 'Deliver application to production'
    required: true
    default: true
  image_name:
    description: 'The name of the image to be published'
    required: true
  version:
    description: 'The version of the application'
    required: true
  ci_github_token:
    description: 'GITHUB_TOKEN with permissions to push to the container registry'
    required: true
  deploy_repo:
    description: 'The name of the repository to deploy the application to'
    required: true
  non_prod_tag:
    description: 'Non production docker image tag'
    required: false
    default: 'nightly'

runs:
  using: composite
  steps:
    - name: OCI image vulnerability scanning
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/${{ inputs.image_name }}:${{ inputs.version }}
        format: 'sarif'
        output: 'trivy-results-oci-image.sarif'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: 'trivy-results-oci-image.sarif'

    - name: Log into GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ci_github_token }}

    - name: Publish container image to GHCR
      if: ${{ inputs.deliver }}
      run: |
        docker push ghcr.io/${{ inputs.image_name }}:${{ inputs.version }}
        docker tag ghcr.io/${{ inputs.image_name }}:${{ inputs.version }} \
            ghcr.io/${{ inputs.image_name }}:latest
        docker push ghcr.io/${{ inputs.image_name }}:latest
      shell: bash

    - name: Publish non-production container image to GHCR ${{ github.repository }}
      if: ${{ !inputs.deliver }}
      run: |
        docker tag ghcr.io/${{ inputs.image_name }}:${{ inputs.version }} \
                    ghcr.io/${{ inputs.image_name }}:${{ inputs.non_prod_tag }}
        docker push ghcr.io/${{ inputs.image_name }}:${{ inputs.non_prod_tag }}
      shell: bash

    - name: Deliver application to production ${{ github.repository }}
      if: ${{ inputs.deliver }}
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.ci_github_token }}
        repository: ${{ github.repository }}
        event-type: app_delivery
        client-payload: '{
          "app_image": "ghcr.io/${{ github.repository }}",
          "app_name": "${{ inputs.app_repo }}",
          "app_version": "${{ inputs.version }}"
        }'
