name: Check Project Integrity
description: |
  This workflow checks the integrity of the project by running various checks
  such as Validate Gradle wrapper, Install Tools & Dependencies, and Run Check.

runs:
  using: composite
  steps:
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2.1.3

    - name: Install Tools & Dependencies
      uses: ./.github/actions/install/node

    - name: Run Check
      run: pnpm run check
      shell: bash
