name: Publish to Docker Hub and Deploy
description: Publish the application to Docker Hub and deploy to the main stage

inputs:
  deliver:
    description: 'Deliver application to production'
    required: true
    type: boolean
    default: true
  registry:
    description: 'The container registry to push the image to'
    required: true
    type: string
    default: 'docker.io'
  image_name:
    description: 'The name of the image to be published'
    required: true
    type: string
  version:
    description: 'The version of the application'
    required: true
    type: string
  docker_username:
    description: 'The username for Docker Hub'
    required: true
    type: string
  docker_password:
    description: 'The password for Docker Hub'
    required: true
  docker_image_name:
    description: 'The name of the image to be published'
    required: true
    type: string
    default: 'n4t5u/lyra'
  non_prod_tag:
    description: 'The tag to use for non-production images'
    required: false
    type: string
    default: 'non-prod-${{ inputs.version }}'

runs:
  using: composite
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Publish container image
      if: ${{ inputs.deliver }}
      run: |
        docker tag ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }} ${{ inputs.docker_image_name }}:${{ inputs.version }}
        docker push n4t5u/lyra:${{ inputs.version }}
        docker tag ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }} ${{ inputs.docker_image_name }}:latest
        docker push ${{ inputs.docker_image_name }}:latest
      shell: bash

    - name: Publish non-production container image to Docker Hub
      if: ${{ !inputs.deliver }}
      run: |
        docker tag ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }} ${{ inputs.docker_image_name }}:${{ inputs.non_prod_tag }}
        docker push ${{ inputs.docker_image_name }}:${{ inputs.non_prod_tag }}
      shell: bash
