# Configuration file for the application
server:
  port: 8080
logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.lyra: DEBUG
spring:
  application:
    name: ${application.name}
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

application:
  name: lyra
  description: Lyra is the take note of the future. It's a note taking app that uses AI to help you take notes.
  version: 0.0.1-SNAPSHOT

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, openapi, swagger-ui
notification:
  email:
    sendgrid-api-key: ${SENDGRID_API_KEY:WILL_BE_REPLACED}
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
    csrf:
      enabled: true
