name: Package and Publish 📦
description: |
  This workflow is responsible for packaging and publishing the application
  to the container registry.

  It also performs vulnerability scanning on the OCI image.

  The workflow is triggered after the build stage.

  The workflow is responsible for the following:
  - Install Java Tools & Dependencies
  - Execute Gradle build
  - OCI image vulnerability scanning
  - Upload vulnerability report
  - Log in to Docker Hub

inputs:
  deliver:
    description: 'Deliver application to production'
    required: true
    type: boolean
    default: true
  registry:
    description: 'The container registry to push the image to'
    required: true
    type: string
    default: 'ghcr.io'
  docker_username:
    description: 'The username for Docker Hub'
    required: true
    type: string
  docker_password:
    description: 'The password for Docker Hub'
    required: true
  image_name:
    description: 'The name of the image to be published'
    required: true
    type: string
  version:
    description: 'The version of the application'
    required: true
    type: string
  ci_github_token:
    description: 'GITHUB_TOKEN with permissions to push to the container registry'
    required: true
    type: string
  owner:
    description: 'The owner of the repository'
    required: true
    type: string
  app_repo:
    description: 'The name of the application repository'
    required: true
    type: string
  deploy_repo:
    description: 'The name of the repository to deploy the application to'
    required: true
    type: string



runs:
  using: composite
  steps:
    - name: Install Java Tools & Dependencies
      uses: ./.github/actions/install/java

    - name: Execute Gradle build
      run: |
        chmod +x gradlew
        ./gradlew assemble
        ./gradlew bootBuildImage --imageName ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
      shell: bash

    - name: OCI image vulnerability scanning
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
        format: 'sarif'
        output: 'trivy-results-oci-image.sarif'

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: 'trivy-results-oci-image.sarif'

    - name: Publish container image to GHCR
      uses: ./.github/actions/publish/ghcr
      with:
        deliver: ${{ inputs.deliver }}
        registry: ${{ inputs.registry }}
        image_name: ${{ inputs.image_name }}
        version: ${{ inputs.version }}
        ci_github_token: ${{ inputs.ci_github_token }}
        owner: ${{ inputs.owner }}
        app_repo: ${{ inputs.app_repo }}

    - name: Publish container image to Docker Hub
      uses: ./.github/actions/publish/dockerhub
      with:
        deliver: ${{ inputs.deliver }}
        image_name: ${{ inputs.image_name }}
        version: ${{ inputs.version }}
        docker_username: ${{ inputs.docker_username }}
        docker_password: ${{ inputs.docker_password }}
        docker_image_name: ${{ inputs.image_name }}

    - name: Deliver application to production
      if: ${{ inputs.deliver }}
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.ci_github_token }}
        repository: ${{ inputs.owner }}/${{ inputs.deploy_repo }}
        event-type: app_delivery
        client-payload: '{
          "app_image": "${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.app_repo }}",
          "app_name": "${{ inputs.app_repo }}",
          "app_version": "${{ inputs.version }}"
        }'
